function def_times1 = gaussian_time(R,num,n)

% This functions generates pseudo default stopping times (generated by a
% multinomial gaussian copula with correlation matrix "R") for the "n"
% obligors included in the basket. "num" stands for the number of
% simulations. We call the output of the function "pseudo" cause we still
% have to divide the result of the function by the specific hazard rate.
% But given the relationship h=S/(1-Rec), the ahzard rate will vary at each
% recovery loop, so we will perform the ratio in the CDO_tranche.m
% function.

% Now we use the simulation algorithm for generating normal variates from
% gaussian copula suggested by ELM(01), pag. 26

x1 = zeros(num,n);
y = zeros(num,n);

A=chol(R);
clear R;
z=randn(num,n);
for i=1:num
    y(i,:)=z(i,:)*A;
end

clear A;
clear z;

Gauss_U1=normcdf(y); % 0-1 variates normally distributed
clear y;
x1=-log(Gauss_U1);
clear Gauss_U1;

def_times1=x1; % we do not divide by the hazard rate cause it depends on the recovery rate at each loop
